theme: jekyll-theme-leap-day
markdown:   kramdown
style:  kjhealy
title: Digital CV
description: Ashish Dhiman's CV <br> _Optmisation, Explainable AI, Data Science, Credit Risk, Geopoloitics Enthusiast_
