theme: jekyll-theme-leap-day
markdown:   kramdown
style:  kjhealy
title: Digital CV
description: Optmisation, Explainable AI, Data Science, Credit Risk, Geopolitics Enthusiast
google_analytics: G-TH2FQ5DYD8
